# Quick boot options
sudo: false
cache:
  directories:
    - node_modules

# Ignore version tags
branches:
  except:
    - /^v[0-9]/

# Language options
language: node_js
node_js:
  - '4.1.2'

# Coverage report
after_success:
  - export TRAVIS_PASSED=true
  - npm install codeclimate-test-reporter --global
  - codeclimate-test-reporter < coverage/lcov.info
env:
  global:
    # CODECLIMATE_REPO_TOKEN
    - secure: EKnQGtoAac695g3tlAjp9acQxYDpCL548ZPdbHRlAPFtN8V8/xvOahaqmhimJr9ASnX4lMYd7Q0PNGa6Zdeykjy9cyJndW1bfCHVtHiDOGjjXzXYrd0ZQ7s4PjJu+W3yFtOwyvwH0uVPlf1YDzgde71V6Mkw71bDC8SpvqKN7YEXlQP+d22qV5jijK6Fc6rZzoEZnWR5pJGsRf14oIIYztWCmI9L8HchHuzXihXLGJVJeOGQQRz57FllUaW9qpYkbbh6+QHiKpBxmitvdWoXVdULCu/YbUK12rInZQ8kHoL01lIsZ3dFI9GEGK/UXtPngrwKlgtQ4uMW2uAf4IyRJ6nUlHaqew4XPO3mZNOjbvm7SOGbD0MPYOgCpR00T3FjwYXH4Z1K/2dQtEet47XgiyUiXaX+aILrRGN2l6nxRx2ZxYuRy0NbqRgY69WZz4SEmyoTgPvIxcFCmDyOYSL2PAxw96FH99tncHmXZQqe5S4v3wwSBDoG3O++WZix+UgaVIXFROUIN4nHftQ9krlQjk20HSxwHcKsGxThUsKBZbRC0xmv6skSU5rRVcRFE5NFZYsKyTUSMWgvXolocxKi6ddEFQhk0XzaeZr7iTHjZ3XzHAbcXyVxJclQx2l6kIV6CX3Td3wJaLUSNwnbCtEC+8THo+g+l9f2CZXLojySrCQ=

# Npm publish options
before_deploy:
  - npm install babel@5 --global
deploy:
  provider: npm
  email: i59naga@icloud.com
  api_key:
    secure: oEake3RrV2OLR9RAUvjp8AZWtxA1HFOftQkDOQrolr5hQg0/AvNc9m4NmLh/V/tZ4MjOnCcF5z7k3BTkeTRiXuPkhDcHiVGP09ydCjZof9r2S2dc8mMaqx0aR4KTg6k9pqB8yypW8xa60aci1TP9FMh++6mVFJpFmH97noJc2lnjenI+P3FhND/mxLVq0SJQLqBDVZT7Wnz8svijestOsJTixaQ70UEXhr5UgeTLQFe7W9244AjBK5YxliufA0L/DDVBDEqyxjsmeOR/Io+N0L481zOENi19DNak28nn1rgfWWfoJlupvdOblMB4ZtWsfWf0mz5kTMP681TttO+aKfJ2m76Empt2bhuXZYRZtMJ7u32XJB2of0vY0EmKA2PyIB79GhFjULPvXv1jDQ43B1PxgMuVdfRDIeyQ1Oc75WH7MEaegiJHnblnRIF1ZLlvCrHWA0B27CL4rqZmDb8Z/5IThNc9bNOTEwRoIC/a6CC0aZY5CrkaeQwt2kkw+utQ6gCnAXng4xvBaSVeUFhEjoJn/+SCLQ0dU9enrz2zRayBydVQ81s4coYk1xJ6GeplPnxAhmOgSr+mkzJSGEFaYuIGFWBwOHRZL2Fk3OH+nn1lzpkgM6Bp3m63OJXchlspmSk4/IgIMAIdUCo2RkMtRhHkLQz1tbKQTPWOIivQqMw=
